import { geistSans, geistMono } from "@/lib/fonts";
import "./globals.css";
import { Providers } from './providers'
import RouteGuard from "@/components/RouteGuard";

export const metadata = {
  title: "Team Sync",
  description: "Generated by  create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <RouteGuard>
            {children}
          </RouteGuard>
        </Providers>
      </body>
    </html>
  );
}
