import { geistSans, geistMono } from "@/lib/fonts";
import "./globals.css";

import RouteGuard from "@/components/RouteGuard";
import { Toaster } from 'sonner';

export const metadata = {
  title: "Team Sync",
  description: "Generated by  create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <RouteGuard>
            {children}
            <Toaster 
              position="top-right" 
              duration={4000}
            />
          </RouteGuard>
      </body>
    </html>
  );
}
